### ISSUE TITLE
jQuery 에러

### ISSUE THREAD

**Issue by doortts** [yona-projects/home#3]
![image](https://cloud.githubusercontent.com/assets/520523/25010258/8b9c0b4c-20a4-11e7-92e7-2faabfd8f9ec.png)

@BasixKOR jQuery도 필요한가요?

**Comment by BasixKOR** [comment]
jQuery도 필요합니다. 어제 까먹어버렸네요..

2017년 4월 13일 (목) 오후 11:55, Suwon Chae <notifications@github.com>님이 작성:
